aws:
  cloudwatch_alarm_thresh: 10.0
  ecr_repo_name: csv-to-kinesis-repo
  notifications_email: nastja.makhonina@gmail.com
  kinesis_shard_count: 2
  s3_bucket_name: csv-to-kinesis-bucket
dataset:
  apply_delay: true
  colname_dt: 'tx_datetime'
  delay_ms: -1
  filepath: data/example_dataset.csv
  filepath_processed: data/example_dataset_processed.csv
  first_event_dt: '2024-08-19 15:00:00'
  s3_filepath: data/example_dataset_processed.csv
