[tool.poetry]
name = "csv-to-kinesis-stream"
version = "0.1.0"
description = "Create an AWS Kinesis stream from your CSV file using AWS Lambda, S3 and CDK"
authors = ["nastjamakh <nastja.makhonina.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
constructs = ">=10.0.0,<11.0.0"
aws-cdk-lib = "2.151.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
